//API 1 GET player details
GET http://localhost:3000/players/
###

//API 2 GET Method using playerId
GET http://localhost:3000/players/2/
###

//API 3 PUT Method player details
PUT http://localhost:3000/players/9

{
    "playerName":"Raju"
}
###

//API 4 GET match details
GET http://localhost:3000/matches/12/
###

//API 5 GET match details using player ID
GET http://localhost:3000/players/2/matches
###

//API 6 GET player details using match id
GET http://localhost:3000/matches/2/players
###

//API 7 GET player score using player id
GET http://localhost:3000/players/1/playerScores
###